myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from myapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^$', views.index, name='index'),
    url(r'^articulo/(?P<slug>[-\w]+)/$', views.articulo, name='articulo'),
    url(r'^like/(?P<id>\d+)/(?P<accion>\w+)/$', views.like, name='like'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
#coding: utf8
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.template.defaultfilters import slugify

@python_2_unicode_compatible
class Categoria(models.Model):
	nombre = models.CharField(max_length=25)

	def __str__(self):
		return self.nombre

@python_2_unicode_compatible
class Articulo(models.Model):
	titulo = models.CharField(max_length=100)
	slug = models.SlugField(unique=True, blank=True, null=True)
	portada = models.ImageField(upload_to='portadas', default='portada01.png', blank=True, null=True)
	autor = models.ForeignKey(User)
	categoria = models.ForeignKey(Categoria, blank=False, null=False)
	fecha = models.DateTimeField(auto_now_add=True)
	contenido = models.TextField()
	likes = models.SmallIntegerField(default=0)
	dislikes = models.SmallIntegerField(default=0)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.titulo)
		super(Articulo, self).save(*args, **kwargs)

	def __str__(self):
		return self.titulo + ': ' + self.slug 

@python_2_unicode_compatible
class Comentario(models.Model):
	fecha = models.DateTimeField(auto_now_add=True)
	contenido = models.TextField()
	articulo = models.ForeignKey(Articulo)

	def __str__(self):
		return self.contenido

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Articulo

def like(request, id, accion):
	# paso 1: crear el objeto
	art = Articulo.objects.get(pk=id)

	# paso 2: editar el objeto
	if accion == 'like':
		art.likes += 1
	else:
		art.dislikes += 1

	# paso 3: guardar los cambios
	art.save()

	return HttpResponseRedirect(reverse('articulo', args=[art.slug]))

def articulo(request, slug):
	art = Articulo.objects.get(slug=slug)
	return render(request, 'articulo.html', {'articulo': art})

def index(request):
	# SELECT * FROM Articulos ORDER BY id DESC: queryset
	articulos = Articulo.objects.all().order_by('-id')

	return render(request, 'index.html', {'articulos':articulos})

myapp/templates/articulo.html
{% extends "base.html" %}

{% block container %}
	<article>
		<h2>{{ articulo.titulo }}</h2>
		Publicado hace <strong>{{ articulo.fecha|timesince }}</strong> |
        Por <strong>{{ articulo.autor.get_full_name }}</strong> |
        <strong>{{ articulo.likes }}</strong> me gusta
        
        <img class="portada" src="/media/{{ articulo.portada }}" alt="portada">

        <div>
            {{ articulo.contenido|linebreaks }}
        </div>

        <p>
        	<a href="{% url 'like' articulo.id 'like' %}" class="btn btn-primary">
        		<span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
        		Me gusta
        		({{ articulo.likes }})      		
        	</a>
        	<a href="{% url 'like' articulo.id 'dislike' %}" class="btn btn-danger">
        		<span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
        		No me gusta
        		({{ articulo.dislikes }})      		
        	</a>
        </p>
	</article>

	<h2>Comentarios</h2>

	{% for comentario in articulo.comentario_set.all %}
		<p class="well">
			Publicado hace <strong>{{ comentario.fecha|timesince }}</strong> <br>
			{{ comentario }}
		</p>
	{% endfor %}
{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Un blog de tecnología</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'myapp/bootstrap/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'myapp/css/mis_estilos.css' %}">

</head>
<body>
	<div class="container">
		<h1>Un blog de tecnología</h1>

		<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="/">NW</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li class="active"><a href="#">Inicio <span class="sr-only">(current)</span></a></li>
		        <li><a href="#">Programación</a></li>
		        <li><a href="#">Bases de datos</a></li>
		        <li><a href="#">Redes</a></li>
		        <li><a href="#">Diseño</a></li>
		        
		      </ul>
		      
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="#">Link</a></li>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
		          <ul class="dropdown-menu">
		            <li><a href="#">Action</a></li>
		            <li><a href="#">Another action</a></li>
		            <li><a href="#">Something else here</a></li>
		            <li role="separator" class="divider"></li>
		            <li><a href="#">Separated link</a></li>
		          </ul>
		        </li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>

		{% block container %}{% endblock %}
	</div>
</body>
</html>

myapp/templates/index.html
{% extends "base.html" %}

{% block container %}
    <div class="row">
        <div class="col-md-7">
            {% for articulo in articulos %}
        
                <article>
                    <h2><a href="{% url 'articulo' articulo.slug %}">{{ articulo.titulo }}</a></h2>
                    Publicado hace <strong>{{ articulo.fecha|timesince }}</strong> |
                    Por <strong>{{ articulo.autor.get_full_name }}</strong> |
                    <strong>{{ articulo.likes }}</strong> me gusta
                    
                    <img class="portada" src="/media/{{ articulo.portada }}" alt="portada">

                    <div>
                        {{ articulo.contenido|linebreaks|truncatewords:30 }}
                    </div>

                    <p>
                        <a class="btn btn-success btn-sm" href="{% url 'articulo' articulo.slug %}">
                            Continuar leyendo
                        </a>
                    </p>
                </article>
                <hr>

            {% endfor %}
        </div>
        <div class="col-md-5"></div>
    </div>
{% endblock %}